"""应用基础配置。"""

APP_TITLE = "A股尾盘策略筛选系统"
APP_DESCRIPTION = "基于公开行情数据的尾盘策略辅助分析工具"
DATA_CACHE_TTL = 60
SCAN_HISTORY_DATABASE = "data/scan_history.db"

# 第一版尾盘筛选条件
MAIN_BOARD_CODE_PREFIXES = ("60", "00")
EXCLUDED_NAME_KEYWORDS = ("ST", "*ST", "退市")
PRICE_CHANGE_MIN = 3.0
PRICE_CHANGE_MAX = 8.0
VOLUME_RATIO_MIN = 1.0
TURNOVER_RATE_MIN = 5.0
TURNOVER_RATE_MAX = 10.0
MARKET_CAP_MIN = 3_000_000_000
MARKET_CAP_MAX = 30_000_000_000
MARKET_CAP_UNIT = 100_000_000

# 最近涨停二次筛选条件
HISTORY_TRADING_DAYS = 20
HISTORY_MIN_FETCH_TRADING_DAYS = 25
HISTORY_CALENDAR_LOOKBACK_DAYS = 90
MAIN_BOARD_LIMIT_UP_RATE = 0.10
PRICE_TICK_SIZE = 0.01
LIMIT_UP_PRICE_TOLERANCE = 0.001
HISTORY_REQUEST_INTERVAL_SECONDS = 0.3
HISTORY_CACHE_TTL = 3600

# 免费分钟行情的尾盘结构近似判断
LATE_SESSION_START_TIME = "14:30:00"
LATE_SESSION_END_TIME = "15:00:00"
LATE_MIN_REQUIRED_MINUTES = 10
LATE_DATA_COMPLETENESS_MIN = 0.80
LATE_VWAP_ABOVE_RATIO_MIN = 0.80
LATE_MAX_DRAWDOWN = 0.01
LATE_LAST_MINUTES = 10
LATE_LAST_MINUTES_MAX_DROP = -0.008
LATE_RAPID_DROP_MAX_CONSECUTIVE = 3
LATE_VOLUME_BASELINE_MINUTES = 30
LATE_VOLUME_EXPANSION_RATIO = 1.50
MINUTE_VOLUME_SHARE_MULTIPLIER = 100
INTRADAY_REQUEST_INTERVAL_SECONDS = 0.3
INTRADAY_CACHE_TTL = 300
LATE_SCORE_VWAP_WEIGHT = 40
LATE_SCORE_DRAWDOWN_WEIGHT = 30
LATE_SCORE_TREND_WEIGHT = 20
LATE_SCORE_VOLUME_WEIGHT = 10

# 100 分评分系统
SCORE_FUNDS_MAX = 30
SCORE_SECTOR_MAX = 20
SCORE_TECHNICAL_MAX = 20
SCORE_LATE_SESSION_MAX = 20
SCORE_MARKET_SENTIMENT_MAX = 10
SCORE_FUND_FLOW_PART = 20
SCORE_VOLUME_RATIO_PART = 10
SCORE_TECH_CHANGE_PART = 10
SCORE_TECH_CLOSE_POSITION_PART = 10
FUND_FLOW_NET_RATIO_MIN = -5.0
FUND_FLOW_NET_RATIO_MAX = 15.0
SCORE_VOLUME_RATIO_MIN = 1.0
SCORE_VOLUME_RATIO_MAX = 3.0
SECTOR_CHANGE_SCORE_MIN = 0.0
SECTOR_CHANGE_SCORE_MAX = 5.0
SCORE_MINIMUM = 80.0
SCORE_CAUTION_MAX = 84.9999
SCORE_WATCH_MIN = 85.0
SCORE_WATCH_MAX = 89.9999
SCORE_FOCUS_MIN = 90.0
SCORING_REQUEST_INTERVAL_SECONDS = 0.3
SCORING_CACHE_TTL = 1800
SCORING_MAX_RESULTS = 10
