"""应用基础配置。"""

APP_TITLE = "A股尾盘策略筛选系统"
APP_DESCRIPTION = "基于公开行情数据的尾盘策略辅助分析工具"
DATA_CACHE_TTL = 60
SCAN_HISTORY_DATABASE = "data/scan_history.db"

# 每日复盘。收益统一以推荐日不复权收盘价为基准；历史日线也使用不复权口径。
STRATEGY_VERSION = "v2.1"
REVIEW_TAKE_PROFIT = 0.03
REVIEW_STOP_LOSS = -0.02
REVIEW_COMMISSION_RATE = 0.0003
REVIEW_STAMP_DUTY_RATE = 0.0005
REVIEW_SLIPPAGE_RATE = 0.0005
REVIEW_MIN_OPTIMIZATION_DAYS = 20
REVIEW_MIN_OPTIMIZATION_SAMPLES = 100
REVIEW_FULL_MODEL_DAYS = 60

# 第一版尾盘筛选条件
MAIN_BOARD_CODE_PREFIXES = ("60", "00")
EXCLUDED_NAME_KEYWORDS = ("ST", "*ST", "退市")
PRICE_CHANGE_MIN = 3.0
PRICE_CHANGE_MAX = 5.0
VOLUME_RATIO_MIN = 1.0
TURNOVER_RATE_MIN = 5.0
TURNOVER_RATE_MAX = 10.0
MARKET_CAP_MIN = 3_000_000_000
MARKET_CAP_MAX = 30_000_000_000
MARKET_CAP_UNIT = 100_000_000
TARGET_SELECTION_COUNT = 5
ENRICHMENT_CANDIDATE_LIMIT = 30
LEVEL1_PRICE_CHANGE_MIN = 2.0
LEVEL1_PRICE_CHANGE_MAX = 8.0
LEVEL1_TURNOVER_RATE_MIN = 3.0
LEVEL1_TURNOVER_RATE_MAX = 12.0
LEVEL2_VOLUME_RATIO_MIN = 0.8
LEVEL2_MARKET_CAP_MIN = 2_000_000_000
LEVEL2_MARKET_CAP_MAX = 50_000_000_000

# 最近涨停二次筛选条件
HISTORY_TRADING_DAYS = 20
HISTORY_MIN_FETCH_TRADING_DAYS = 25
HISTORY_CALENDAR_LOOKBACK_DAYS = 90
MAIN_BOARD_LIMIT_UP_RATE = 0.10
PRICE_TICK_SIZE = 0.01
LIMIT_UP_PRICE_TOLERANCE = 0.001
HISTORY_REQUEST_INTERVAL_SECONDS = 0.3
HISTORY_CACHE_TTL = 21600

# 免费分钟行情的尾盘结构近似判断
LATE_SESSION_START_TIME = "14:30:00"
LATE_SESSION_END_TIME = "15:00:00"
LATE_MIN_REQUIRED_MINUTES = 10
LATE_DATA_COMPLETENESS_MIN = 0.80
LATE_VWAP_ABOVE_RATIO_MIN = 0.80
LATE_MAX_DRAWDOWN = 0.01
LATE_LAST_MINUTES = 10
LATE_LAST_MINUTES_MAX_DROP = -0.008
LATE_RAPID_DROP_MAX_CONSECUTIVE = 3
LATE_VOLUME_BASELINE_MINUTES = 30
LATE_VOLUME_EXPANSION_RATIO = 1.50
MINUTE_VOLUME_SHARE_MULTIPLIER = 100
INTRADAY_REQUEST_INTERVAL_SECONDS = 0.5
INTRADAY_CACHE_TTL = 90
LATE_SCORE_VWAP_WEIGHT = 40
LATE_SCORE_DRAWDOWN_WEIGHT = 30
LATE_SCORE_TREND_WEIGHT = 20
LATE_SCORE_VOLUME_WEIGHT = 10

# 100 分评分系统（缺失分项按可用权重重新归一化）
SCORE_LATE_SESSION_MAX = 20
SCORE_VOLUME_MAX = 15
SCORE_FUNDS_MAX = 15
SCORE_SECTOR_MAX = 15
SCORE_TREND_MAX = 15
SCORE_TURNOVER_MAX = 10
SCORE_ACTIVITY_MAX = 10
# 历史回测模块仍使用旧版分项名称；保留兼容值，实时选股不再使用。
SCORE_MARKET_SENTIMENT_MAX = 10
SCORE_FUND_FLOW_PART = 20
SCORE_VOLUME_RATIO_PART = 10
SCORE_TECH_CHANGE_PART = 10
SCORE_TECH_CLOSE_POSITION_PART = 10
SCORE_VOLUME_RATIO_MIN = 1.0
SCORE_VOLUME_RATIO_MAX = 3.0
FUND_FLOW_NET_RATIO_MIN = -5.0
FUND_FLOW_NET_RATIO_MAX = 15.0
SCORE_VOLUME_RATIO_MIN = 1.0
SCORE_VOLUME_RATIO_MAX = 3.0
SECTOR_CHANGE_SCORE_MIN = 0.0
SECTOR_CHANGE_SCORE_MAX = 5.0
SCORE_MINIMUM = 80.0
SCORE_CAUTION_MAX = 84.9999
SCORE_WATCH_MIN = 85.0
SCORE_WATCH_MAX = 89.9999
SCORE_FOCUS_MIN = 90.0
SCORING_REQUEST_INTERVAL_SECONDS = 0.3
SCORING_CACHE_TTL = 86400
SCORING_MAX_RESULTS = TARGET_SELECTION_COUNT
DEEP_ANALYSIS_LIMIT = 12
SCAN_MAX_WORKERS = 4
SCAN_TARGET_SECONDS = 30
SCAN_SOFT_LIMIT_SECONDS = 60
SCAN_HARD_LIMIT_SECONDS = 90

# 历史回测（严格使用筛选日及此前可得数据）
BACKTEST_MAX_TRADING_DAYS = 10
BACKTEST_DEFAULT_RANGE_TRADING_DAYS = 20
BACKTEST_DEFAULT_MAX_STOCKS = 5
BACKTEST_MAX_STOCKS_LIMIT = 10
BACKTEST_DATA_CACHE_TTL = 21600
BACKTEST_DAILY_BATCH_SIZE = 300
BACKTEST_BASIC_BATCH_SIZE = 500
BACKTEST_REQUEST_INTERVAL_SECONDS = 0.15
BACKTEST_MINUTE_LOOKBACK_TRADING_DAYS = 5
BACKTEST_BUY_TIME = "14:50:00"
BACKTEST_MARKET_CLOSE_TIME = "15:05:00"
